-- =============================================================================
-- 12. REPORT TEMPLATE
-- Tabel metadata untuk desain dokumen cetakan (Simple Report Engine)
-- =============================================================================
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ODAF;

CREATE TABLE RPT_TEMPLATE (
    OBJECT_ID       RAW(16) DEFAULT SYS_GUID() NOT NULL,
    APPLICATION_ID  RAW(16) NOT NULL,
    PAGE_ID         RAW(16) NOT NULL,
    OBJECT_CODE     VARCHAR2(100 CHAR) NOT NULL,
    OBJECT_NAME     VARCHAR2(200 CHAR) NOT NULL,
    PAGE_SIZE       VARCHAR2(20 CHAR) DEFAULT 'A4',
    ORIENTATION     VARCHAR2(20 CHAR) DEFAULT 'PORTRAIT',
    HTML_CONTENT    CLOB,
    CSS_CONTENT     CLOB,
    IS_DEFAULT      NUMBER(1) DEFAULT 0,
    STATUS          VARCHAR2(30 CHAR) DEFAULT 'PUBLISHED',
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP WITH TIME ZONE,
    CREATED_BY      VARCHAR2(100 CHAR),
    UPDATED_BY      VARCHAR2(100 CHAR),
    CONSTRAINT PK_RPT_TEMPLATE PRIMARY KEY (OBJECT_ID),
    CONSTRAINT FK_RPT_TEMPLATE_APP FOREIGN KEY (APPLICATION_ID) REFERENCES SYS_APPLICATION(OBJECT_ID),
    CONSTRAINT FK_RPT_TEMPLATE_PAGE FOREIGN KEY (PAGE_ID) REFERENCES UI_PAGE(OBJECT_ID)
);

CREATE INDEX IDX_RPT_TEMPLATE_PAGE ON RPT_TEMPLATE(PAGE_ID);

-- Menambahkan tabel RPT_TEMPLATE ke kamus sistem ODAF agar bisa di-export jika perlu
INSERT INTO SYS_DICTIONARY (OBJECT_ID, TABLE_NAME, DESCRIPTION, IS_METADATA) 
VALUES (SYS_GUID(), 'RPT_TEMPLATE', 'Document/Report Template Designer', 1);

COMMIT;
