-- =============================================================================
-- ODAF Metadata Repository - Security Domain (SEC_*)
-- gvenzl menjalankan skrip ini sebagai SYS@CDB$ROOT; alihkan ke PDB & schema ODAF.
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ODAF;
--
-- Volume 2 Bab 11 (Security Model), Volume 3 Bab 18 (Security Engine)
-- RBAC: user, role, permission, dan tabel relasi. FK selalu -> OBJECT_ID.
-- =============================================================================

-- Pengguna platform (APP_USER/SEC_USER; hindari reserved word USER).
CREATE TABLE IF NOT EXISTS SEC_USER (
    OBJECT_ID      RAW(16)                    DEFAULT SYS_GUID() NOT NULL,
    OBJECT_CODE    VARCHAR2(100 CHAR)         NOT NULL,   -- username
    OBJECT_NAME    VARCHAR2(200 CHAR)         NOT NULL,   -- nama tampilan
    EMAIL          VARCHAR2(200 CHAR),
    PASSWORD_HASH  VARCHAR2(255 CHAR),
    ACTIVE_FLAG    NUMBER(1)                  DEFAULT 1 NOT NULL,
    DESCRIPTION    CLOB,
    VERSION_NO     NUMBER(10)                 DEFAULT 1 NOT NULL,
    STATUS         VARCHAR2(30 CHAR)          DEFAULT 'PUBLISHED' NOT NULL,
    CREATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY     RAW(16),
    UPDATED_BY     RAW(16),
    CONSTRAINT PK_SEC_USER PRIMARY KEY (OBJECT_ID),
    CONSTRAINT UK_SEC_USER_CODE UNIQUE (OBJECT_CODE),
    CONSTRAINT CK_SEC_USER_ACTIVE CHECK (ACTIVE_FLAG IN (0, 1))
);

-- Role.
CREATE TABLE IF NOT EXISTS SEC_ROLE (
    OBJECT_ID      RAW(16)                    DEFAULT SYS_GUID() NOT NULL,
    OBJECT_CODE    VARCHAR2(100 CHAR)         NOT NULL,
    OBJECT_NAME    VARCHAR2(200 CHAR)         NOT NULL,
    DESCRIPTION    CLOB,
    VERSION_NO     NUMBER(10)                 DEFAULT 1 NOT NULL,
    STATUS         VARCHAR2(30 CHAR)          DEFAULT 'PUBLISHED' NOT NULL,
    APPLICATION_ID RAW(16),
    CREATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY     RAW(16),
    UPDATED_BY     RAW(16),
    CONSTRAINT PK_SEC_ROLE PRIMARY KEY (OBJECT_ID),
    CONSTRAINT UK_SEC_ROLE_CODE UNIQUE (OBJECT_CODE),
    CONSTRAINT FK_SEC_ROLE_APP FOREIGN KEY (APPLICATION_ID) REFERENCES APP_APPLICATION (OBJECT_ID)
);

-- Permission granular (menu/form/field/button/object + action).
CREATE TABLE IF NOT EXISTS SEC_PERMISSION (
    OBJECT_ID        RAW(16)                  DEFAULT SYS_GUID() NOT NULL,
    OBJECT_CODE      VARCHAR2(100 CHAR)       NOT NULL,
    OBJECT_NAME      VARCHAR2(200 CHAR)       NOT NULL,
    PERMISSION_TYPE  VARCHAR2(30 CHAR)        NOT NULL,   -- MENU|FORM|FIELD|BUTTON|OBJECT
    TARGET_OBJECT_ID RAW(16),                             -- objek yang diproteksi
    ACTION_CODE      VARCHAR2(30 CHAR)        NOT NULL,   -- READ|CREATE|UPDATE|DELETE|EXECUTE
    DESCRIPTION      CLOB,
    VERSION_NO       NUMBER(10)               DEFAULT 1 NOT NULL,
    STATUS           VARCHAR2(30 CHAR)        DEFAULT 'PUBLISHED' NOT NULL,
    CREATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       RAW(16),
    UPDATED_BY       RAW(16),
    CONSTRAINT PK_SEC_PERMISSION PRIMARY KEY (OBJECT_ID),
    CONSTRAINT UK_SEC_PERMISSION_CODE UNIQUE (OBJECT_CODE),
    CONSTRAINT CK_SEC_PERMISSION_TYPE CHECK (PERMISSION_TYPE IN ('MENU','FORM','FIELD','BUTTON','OBJECT'))
);

-- Relasi user <-> role.
CREATE TABLE IF NOT EXISTS SEC_USER_ROLE (
    USER_ID    RAW(16) NOT NULL,
    ROLE_ID    RAW(16) NOT NULL,
    CONSTRAINT PK_SEC_USER_ROLE PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_SEC_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES SEC_USER (OBJECT_ID),
    CONSTRAINT FK_SEC_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SEC_ROLE (OBJECT_ID)
);

-- Relasi role <-> permission.
CREATE TABLE IF NOT EXISTS SEC_ROLE_PERMISSION (
    ROLE_ID        RAW(16) NOT NULL,
    PERMISSION_ID  RAW(16) NOT NULL,
    CONSTRAINT PK_SEC_ROLE_PERMISSION PRIMARY KEY (ROLE_ID, PERMISSION_ID),
    CONSTRAINT FK_SEC_ROLE_PERM_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SEC_ROLE (OBJECT_ID),
    CONSTRAINT FK_SEC_ROLE_PERM_PERM FOREIGN KEY (PERMISSION_ID) REFERENCES SEC_PERMISSION (OBJECT_ID)
);

CREATE INDEX IF NOT EXISTS IDX_SEC_PERMISSION_TARGET ON SEC_PERMISSION (TARGET_OBJECT_ID);
CREATE INDEX IF NOT EXISTS IDX_SEC_USER_ROLE_ROLE ON SEC_USER_ROLE (ROLE_ID);
