-- =============================================================================
-- ODAF Metadata Repository - Application Domain (APP_*)
-- gvenzl menjalankan skrip ini sebagai SYS@CDB$ROOT; alihkan ke PDB & schema ODAF.
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ODAF;
--
-- Volume 2 Bab 12 (Application Metadata)
-- Hirarki: APPLICATION -> MODULE -> MENU (-> PAGE)
-- =============================================================================

CREATE TABLE IF NOT EXISTS APP_APPLICATION (
    OBJECT_ID      RAW(16)                    DEFAULT SYS_GUID() NOT NULL,
    OBJECT_CODE    VARCHAR2(100 CHAR)         NOT NULL,
    OBJECT_NAME    VARCHAR2(200 CHAR)         NOT NULL,
    DESCRIPTION    CLOB,
    VERSION_NO     NUMBER(10)                 DEFAULT 1 NOT NULL,
    STATUS         VARCHAR2(30 CHAR)          DEFAULT 'DRAFT' NOT NULL,
    CREATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY     RAW(16),
    UPDATED_BY     RAW(16),
    CONSTRAINT PK_APP_APPLICATION PRIMARY KEY (OBJECT_ID),
    CONSTRAINT UK_APP_APPLICATION_CODE UNIQUE (OBJECT_CODE)
);

CREATE TABLE IF NOT EXISTS APP_MODULE (
    OBJECT_ID      RAW(16)                    DEFAULT SYS_GUID() NOT NULL,
    APPLICATION_ID RAW(16)                    NOT NULL,
    OBJECT_CODE    VARCHAR2(100 CHAR)         NOT NULL,
    OBJECT_NAME    VARCHAR2(200 CHAR)         NOT NULL,
    DISPLAY_ORDER  NUMBER(10)                 DEFAULT 0 NOT NULL,
    DESCRIPTION    CLOB,
    VERSION_NO     NUMBER(10)                 DEFAULT 1 NOT NULL,
    STATUS         VARCHAR2(30 CHAR)          DEFAULT 'DRAFT' NOT NULL,
    CREATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY     RAW(16),
    UPDATED_BY     RAW(16),
    CONSTRAINT PK_APP_MODULE PRIMARY KEY (OBJECT_ID),
    CONSTRAINT UK_APP_MODULE_CODE UNIQUE (APPLICATION_ID, OBJECT_CODE),
    CONSTRAINT FK_APP_MODULE_APP FOREIGN KEY (APPLICATION_ID) REFERENCES APP_APPLICATION (OBJECT_ID)
);

CREATE TABLE IF NOT EXISTS APP_MENU (
    OBJECT_ID      RAW(16)                    DEFAULT SYS_GUID() NOT NULL,
    MODULE_ID      RAW(16)                    NOT NULL,
    PARENT_MENU_ID RAW(16),                              -- self-reference untuk submenu
    PAGE_ID        RAW(16),                              -- halaman yang dibuka (opsional)
    OBJECT_CODE    VARCHAR2(100 CHAR)         NOT NULL,
    OBJECT_NAME    VARCHAR2(200 CHAR)         NOT NULL,
    ICON           VARCHAR2(100 CHAR),
    DISPLAY_ORDER  NUMBER(10)                 DEFAULT 0 NOT NULL,
    VISIBLE_FLAG   NUMBER(1)                  DEFAULT 1 NOT NULL,
    DESCRIPTION    CLOB,
    VERSION_NO     NUMBER(10)                 DEFAULT 1 NOT NULL,
    STATUS         VARCHAR2(30 CHAR)          DEFAULT 'DRAFT' NOT NULL,
    CREATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY     RAW(16),
    UPDATED_BY     RAW(16),
    CONSTRAINT PK_APP_MENU PRIMARY KEY (OBJECT_ID),
    CONSTRAINT UK_APP_MENU_CODE UNIQUE (MODULE_ID, OBJECT_CODE),
    CONSTRAINT CK_APP_MENU_VISIBLE CHECK (VISIBLE_FLAG IN (0, 1)),
    CONSTRAINT FK_APP_MENU_MODULE FOREIGN KEY (MODULE_ID) REFERENCES APP_MODULE (OBJECT_ID),
    CONSTRAINT FK_APP_MENU_PARENT FOREIGN KEY (PARENT_MENU_ID) REFERENCES APP_MENU (OBJECT_ID)
);

CREATE INDEX IF NOT EXISTS IDX_APP_MODULE_APP ON APP_MODULE (APPLICATION_ID);
CREATE INDEX IF NOT EXISTS IDX_APP_MENU_MODULE ON APP_MENU (MODULE_ID);
CREATE INDEX IF NOT EXISTS IDX_APP_MENU_PARENT ON APP_MENU (PARENT_MENU_ID);
