-- =============================================================================
-- ODAF Metadata Repository - UI Domain (UI_*)
-- gvenzl menjalankan skrip ini sebagai SYS@CDB$ROOT; alihkan ke PDB & schema ODAF.
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ODAF;
--
-- Volume 2 Bab 13 (UI Metadata), Volume 3 Bab 14 (UI Rendering Engine)
-- PAGE (form/grid) dan FIELD dinamis. Form/grid digenerate dari metadata ini.
-- =============================================================================

CREATE TABLE IF NOT EXISTS UI_PAGE (
    OBJECT_ID      RAW(16)                    DEFAULT SYS_GUID() NOT NULL,
    APPLICATION_ID RAW(16)                    NOT NULL,
    DATASET_ID     RAW(16),                              -- sumber data halaman
    OBJECT_CODE    VARCHAR2(100 CHAR)         NOT NULL,
    OBJECT_NAME    VARCHAR2(200 CHAR)         NOT NULL,
    TITLE          VARCHAR2(200 CHAR),
    PAGE_TYPE      VARCHAR2(30 CHAR)          NOT NULL,   -- FORM|GRID|DASHBOARD
    LAYOUT_TYPE    VARCHAR2(30 CHAR)          DEFAULT 'SINGLE_COLUMN' NOT NULL,
    DETAIL_CONFIG  CLOB,                                 -- konfigurasi grid detail (JSON): [{pageCode, fkColumn, title}]
    DESCRIPTION    CLOB,
    VERSION_NO     NUMBER(10)                 DEFAULT 1 NOT NULL,
    STATUS         VARCHAR2(30 CHAR)          DEFAULT 'DRAFT' NOT NULL,
    CREATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY     RAW(16),
    UPDATED_BY     RAW(16),
    CONSTRAINT PK_UI_PAGE PRIMARY KEY (OBJECT_ID),
    CONSTRAINT UK_UI_PAGE_CODE UNIQUE (APPLICATION_ID, OBJECT_CODE),
    CONSTRAINT CK_UI_PAGE_TYPE CHECK (PAGE_TYPE IN ('FORM','GRID','DASHBOARD')),
    CONSTRAINT FK_UI_PAGE_APP FOREIGN KEY (APPLICATION_ID) REFERENCES APP_APPLICATION (OBJECT_ID),
    CONSTRAINT FK_UI_PAGE_DATASET FOREIGN KEY (DATASET_ID) REFERENCES DS_DATASET (OBJECT_ID)
);

CREATE TABLE IF NOT EXISTS UI_FIELD (
    OBJECT_ID        RAW(16)                  DEFAULT SYS_GUID() NOT NULL,
    PAGE_ID          RAW(16)                  NOT NULL,
    LOV_ID           RAW(16),                            -- referensi LOV (opsional)
    LOV_LABEL_COLUMN VARCHAR2(128 CHAR),                 -- kolom tujuan label LOV (opsional)
    OBJECT_CODE      VARCHAR2(100 CHAR)       NOT NULL,
    OBJECT_NAME    VARCHAR2(200 CHAR)         NOT NULL,
    LABEL          VARCHAR2(200 CHAR),
    COLUMN_NAME    VARCHAR2(128 CHAR)         NOT NULL,   -- kolom pada tabel sumber
    FIELD_TYPE     VARCHAR2(40 CHAR)          NOT NULL,   -- TEXT|NUMBER|DATE|COMBO|CHECKBOX|TEXTAREA|...
    DATA_TYPE      VARCHAR2(40 CHAR)          DEFAULT 'STRING' NOT NULL,
    DISPLAY_ORDER  NUMBER(10)                 DEFAULT 0 NOT NULL,
    REQUIRED_FLAG  NUMBER(1)                  DEFAULT 0 NOT NULL,
    VISIBLE_FLAG   NUMBER(1)                  DEFAULT 1 NOT NULL,
    READONLY_FLAG  NUMBER(1)                  DEFAULT 0 NOT NULL,
    DEFAULT_VALUE  VARCHAR2(4000 CHAR),
    FIELD_CONFIG   CLOB,                                 -- konfigurasi format (JSON): date/number/dll
    VERSION_NO     NUMBER(10)                 DEFAULT 1 NOT NULL,
    STATUS         VARCHAR2(30 CHAR)          DEFAULT 'DRAFT' NOT NULL,
    CREATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY     RAW(16),
    UPDATED_BY     RAW(16),
    CONSTRAINT PK_UI_FIELD PRIMARY KEY (OBJECT_ID),
    CONSTRAINT UK_UI_FIELD_CODE UNIQUE (PAGE_ID, OBJECT_CODE),
    CONSTRAINT CK_UI_FIELD_REQUIRED CHECK (REQUIRED_FLAG IN (0, 1)),
    CONSTRAINT CK_UI_FIELD_VISIBLE CHECK (VISIBLE_FLAG IN (0, 1)),
    CONSTRAINT CK_UI_FIELD_READONLY CHECK (READONLY_FLAG IN (0, 1)),
    CONSTRAINT FK_UI_FIELD_PAGE FOREIGN KEY (PAGE_ID) REFERENCES UI_PAGE (OBJECT_ID),
    CONSTRAINT FK_UI_FIELD_LOV FOREIGN KEY (LOV_ID) REFERENCES DS_LOV (OBJECT_ID)
);

CREATE INDEX IF NOT EXISTS IDX_UI_PAGE_APP ON UI_PAGE (APPLICATION_ID);
CREATE INDEX IF NOT EXISTS IDX_UI_PAGE_DATASET ON UI_PAGE (DATASET_ID);
CREATE INDEX IF NOT EXISTS IDX_UI_FIELD_PAGE ON UI_FIELD (PAGE_ID);
