-- =============================================================================
-- ODAF Metadata Repository - Validation Domain (VAL_*)
-- gvenzl menjalankan skrip ini sebagai SYS@CDB$ROOT; alihkan ke PDB & schema ODAF.
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ODAF;
--
-- Volume 2 Bab 16 (Validation Metadata), Volume 3 Bab 13 (Rule Engine)
-- Aturan validasi metadata-driven; dievaluasi sebelum eksekusi dataset.
-- =============================================================================

CREATE TABLE IF NOT EXISTS VAL_RULE (
    OBJECT_ID      RAW(16)                    DEFAULT SYS_GUID() NOT NULL,
    OBJECT_CODE    VARCHAR2(100 CHAR)         NOT NULL,
    OBJECT_NAME    VARCHAR2(200 CHAR)         NOT NULL,
    TARGET_TYPE    VARCHAR2(30 CHAR)          NOT NULL,   -- FIELD|RECORD|DATASET
    DATASET_ID     RAW(16),
    FIELD_ID       RAW(16),
    RULE_TYPE      VARCHAR2(40 CHAR)          NOT NULL,   -- REQUIRED|MIN_LENGTH|MAX_LENGTH|MIN_VALUE|MAX_VALUE|REGEX|UNIQUE|FOREIGN_KEY|FORMULA|CONDITIONAL
    RULE_EXPRESSION CLOB,                                 -- parameter/ekspresi rule
    ERROR_MESSAGE  VARCHAR2(400 CHAR),
    DISPLAY_ORDER  NUMBER(10)                 DEFAULT 0 NOT NULL,
    ACTIVE_FLAG    NUMBER(1)                  DEFAULT 1 NOT NULL,
    VERSION_NO     NUMBER(10)                 DEFAULT 1 NOT NULL,
    STATUS         VARCHAR2(30 CHAR)          DEFAULT 'DRAFT' NOT NULL,
    CREATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY     RAW(16),
    UPDATED_BY     RAW(16),
    CONSTRAINT PK_VAL_RULE PRIMARY KEY (OBJECT_ID),
    CONSTRAINT UK_VAL_RULE_CODE UNIQUE (OBJECT_CODE),
    CONSTRAINT CK_VAL_RULE_TARGET CHECK (TARGET_TYPE IN ('FIELD','RECORD','DATASET')),
    CONSTRAINT CK_VAL_RULE_ACTIVE CHECK (ACTIVE_FLAG IN (0, 1)),
    CONSTRAINT FK_VAL_RULE_DATASET FOREIGN KEY (DATASET_ID) REFERENCES DS_DATASET (OBJECT_ID),
    CONSTRAINT FK_VAL_RULE_FIELD FOREIGN KEY (FIELD_ID) REFERENCES UI_FIELD (OBJECT_ID)
);

CREATE INDEX IF NOT EXISTS IDX_VAL_RULE_DATASET ON VAL_RULE (DATASET_ID);
CREATE INDEX IF NOT EXISTS IDX_VAL_RULE_FIELD ON VAL_RULE (FIELD_ID);
