-- =============================================================================
-- ODAF Metadata Repository - Workflow Domain (WF_*) + Runtime Instances (RT_*)
-- gvenzl menjalankan skrip ini sebagai SYS@CDB$ROOT; alihkan ke PDB & schema ODAF.
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ODAF;
--
-- Volume 2 Bab 15 (Workflow Metadata), Volume 3 Bab 12 (Workflow Engine)
-- Model F2.1: state machine approval (Workflow -> Activity -> Transition).
-- WF_* = definisi (dikompilasi ke package). RT_WORKFLOW_* = data instance runtime.
-- =============================================================================

-- Definisi workflow yang mengatur sebuah dataset.
CREATE TABLE IF NOT EXISTS WF_WORKFLOW (
    OBJECT_ID      RAW(16)                    DEFAULT SYS_GUID() NOT NULL,
    OBJECT_CODE    VARCHAR2(100 CHAR)         NOT NULL,
    OBJECT_NAME    VARCHAR2(200 CHAR)         NOT NULL,
    DATASET_ID     RAW(16)                    NOT NULL,   -- dataset yang diatur
    STATE_COLUMN   VARCHAR2(128 CHAR),                    -- kolom bisnis cermin state (opsional)
    DESCRIPTION    CLOB,
    VERSION_NO     NUMBER(10)                 DEFAULT 1 NOT NULL,
    STATUS         VARCHAR2(30 CHAR)          DEFAULT 'DRAFT' NOT NULL,
    CREATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY     RAW(16),
    UPDATED_BY     RAW(16),
    CONSTRAINT PK_WF_WORKFLOW PRIMARY KEY (OBJECT_ID),
    CONSTRAINT UK_WF_WORKFLOW_CODE UNIQUE (OBJECT_CODE),
    CONSTRAINT FK_WF_WORKFLOW_DATASET FOREIGN KEY (DATASET_ID) REFERENCES DS_DATASET (OBJECT_ID)
);

-- Activity = simpul state (START/APPROVAL/TASK/DECISION/END).
CREATE TABLE IF NOT EXISTS WF_ACTIVITY (
    OBJECT_ID      RAW(16)                    DEFAULT SYS_GUID() NOT NULL,
    WORKFLOW_ID    RAW(16)                    NOT NULL,
    OBJECT_CODE    VARCHAR2(100 CHAR)         NOT NULL,   -- kode state, mis. DRAFT
    OBJECT_NAME    VARCHAR2(200 CHAR)         NOT NULL,
    ACTIVITY_TYPE  VARCHAR2(30 CHAR)          DEFAULT 'TASK' NOT NULL, -- START|TASK|APPROVAL|DECISION|END
    INITIAL_FLAG   NUMBER(1)                  DEFAULT 0 NOT NULL,
    FINAL_FLAG     NUMBER(1)                  DEFAULT 0 NOT NULL,
    DISPLAY_ORDER  NUMBER(10)                 DEFAULT 0 NOT NULL,
    VERSION_NO     NUMBER(10)                 DEFAULT 1 NOT NULL,
    STATUS         VARCHAR2(30 CHAR)          DEFAULT 'DRAFT' NOT NULL,
    CREATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE   DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY     RAW(16),
    UPDATED_BY     RAW(16),
    CONSTRAINT PK_WF_ACTIVITY PRIMARY KEY (OBJECT_ID),
    CONSTRAINT UK_WF_ACTIVITY_CODE UNIQUE (WORKFLOW_ID, OBJECT_CODE),
    CONSTRAINT CK_WF_ACTIVITY_TYPE CHECK (ACTIVITY_TYPE IN ('START','TASK','APPROVAL','DECISION','END')),
    CONSTRAINT CK_WF_ACTIVITY_INITIAL CHECK (INITIAL_FLAG IN (0, 1)),
    CONSTRAINT CK_WF_ACTIVITY_FINAL CHECK (FINAL_FLAG IN (0, 1)),
    CONSTRAINT FK_WF_ACTIVITY_WF FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW (OBJECT_ID)
);

-- Transition menghubungkan activity + membawa aksi (trigger), guard, dan role.
CREATE TABLE IF NOT EXISTS WF_TRANSITION (
    OBJECT_ID         RAW(16)                 DEFAULT SYS_GUID() NOT NULL,
    WORKFLOW_ID       RAW(16)                 NOT NULL,
    OBJECT_CODE       VARCHAR2(100 CHAR)      NOT NULL,   -- kode transisi unik per workflow
    OBJECT_NAME       VARCHAR2(200 CHAR)      NOT NULL,   -- label tombol, mis. "Ajukan"
    FROM_ACTIVITY_ID  RAW(16)                 NOT NULL,
    TO_ACTIVITY_ID    RAW(16)                 NOT NULL,
    ACTION_CODE       VARCHAR2(50 CHAR)       NOT NULL,   -- SUBMIT|APPROVE|REJECT|...
    CONDITION_EXPR    CLOB,                                -- guard opsional (F2.1: belum dievaluasi)
    REQUIRED_ROLE_ID  RAW(16),                             -- role yang boleh menjalankan (opsional)
    DISPLAY_ORDER     NUMBER(10)              DEFAULT 0 NOT NULL,
    VERSION_NO        NUMBER(10)              DEFAULT 1 NOT NULL,
    STATUS            VARCHAR2(30 CHAR)       DEFAULT 'DRAFT' NOT NULL,
    CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY        RAW(16),
    UPDATED_BY        RAW(16),
    CONSTRAINT PK_WF_TRANSITION PRIMARY KEY (OBJECT_ID),
    CONSTRAINT UK_WF_TRANSITION_CODE UNIQUE (WORKFLOW_ID, OBJECT_CODE),
    CONSTRAINT FK_WF_TRANS_WF FOREIGN KEY (WORKFLOW_ID) REFERENCES WF_WORKFLOW (OBJECT_ID),
    CONSTRAINT FK_WF_TRANS_FROM FOREIGN KEY (FROM_ACTIVITY_ID) REFERENCES WF_ACTIVITY (OBJECT_ID),
    CONSTRAINT FK_WF_TRANS_TO FOREIGN KEY (TO_ACTIVITY_ID) REFERENCES WF_ACTIVITY (OBJECT_ID),
    CONSTRAINT FK_WF_TRANS_ROLE FOREIGN KEY (REQUIRED_ROLE_ID) REFERENCES SEC_ROLE (OBJECT_ID)
);

CREATE INDEX IF NOT EXISTS IDX_WF_ACTIVITY_WF ON WF_ACTIVITY (WORKFLOW_ID);
CREATE INDEX IF NOT EXISTS IDX_WF_TRANS_WF ON WF_TRANSITION (WORKFLOW_ID);
CREATE INDEX IF NOT EXISTS IDX_WF_TRANS_FROM ON WF_TRANSITION (FROM_ACTIVITY_ID);

-- --- Runtime instance data (bukan artefak terkompilasi) --------------------

-- Instance workflow per baris bisnis.
CREATE TABLE IF NOT EXISTS RT_WORKFLOW_INSTANCE (
    OBJECT_ID           RAW(16)              DEFAULT SYS_GUID() NOT NULL,
    WORKFLOW_ID         RAW(16)              NOT NULL,
    DATASET_CODE        VARCHAR2(100 CHAR),
    ENTITY_KEY          VARCHAR2(64 CHAR)    NOT NULL,   -- PK baris bisnis (hex bila RAW)
    CURRENT_ACTIVITY_ID RAW(16)              NOT NULL,
    CURRENT_STATE_CODE  VARCHAR2(100 CHAR)   NOT NULL,
    INSTANCE_STATUS     VARCHAR2(30 CHAR)    DEFAULT 'RUNNING' NOT NULL, -- RUNNING|COMPLETED|CANCELLED
    STARTED_BY          RAW(16),
    STARTED_AT          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RT_WF_INSTANCE PRIMARY KEY (OBJECT_ID),
    CONSTRAINT UK_RT_WF_INSTANCE UNIQUE (WORKFLOW_ID, ENTITY_KEY),
    CONSTRAINT CK_RT_WF_INSTANCE_STATUS CHECK (INSTANCE_STATUS IN ('RUNNING','COMPLETED','CANCELLED'))
);

-- Riwayat transisi instance (append-only).
CREATE TABLE IF NOT EXISTS RT_WORKFLOW_HISTORY (
    OBJECT_ID       RAW(16)                  DEFAULT SYS_GUID() NOT NULL,
    INSTANCE_ID     RAW(16)                  NOT NULL,
    TRANSITION_ID   RAW(16),
    ACTION_CODE     VARCHAR2(50 CHAR)        NOT NULL,
    FROM_STATE_CODE VARCHAR2(100 CHAR),
    TO_STATE_CODE   VARCHAR2(100 CHAR),
    ACTOR_ID        RAW(16),
    COMMENTS        VARCHAR2(2000 CHAR),
    EVENT_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RT_WF_HISTORY PRIMARY KEY (OBJECT_ID),
    CONSTRAINT FK_RT_WF_HISTORY_INST FOREIGN KEY (INSTANCE_ID) REFERENCES RT_WORKFLOW_INSTANCE (OBJECT_ID)
);

CREATE INDEX IF NOT EXISTS IDX_RT_WF_INSTANCE_WF ON RT_WORKFLOW_INSTANCE (WORKFLOW_ID);
CREATE INDEX IF NOT EXISTS IDX_RT_WF_HISTORY_INST ON RT_WORKFLOW_HISTORY (INSTANCE_ID);
