-- =============================================================================
-- ODAF Metadata Repository - Notification Domain (NTF_*) + Runtime (RT_*)
-- gvenzl menjalankan skrip ini sebagai SYS@CDB$ROOT; alihkan ke PDB & schema ODAF.
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ODAF;
--
-- Volume 2 Bab 18 (Notification Metadata), Volume 3 Bab 15 (Notification Engine)
-- Model F2.2: event -> subscription -> notification(template) -> recipient -> channel.
-- NTF_* = definisi (dikompilasi). RT_NOTIFICATION = instance pengiriman/in-app.
-- =============================================================================

-- Definisi notifikasi reusable (template + channel default).
CREATE TABLE IF NOT EXISTS NTF_NOTIFICATION (
    OBJECT_ID        RAW(16)                  DEFAULT SYS_GUID() NOT NULL,
    OBJECT_CODE      VARCHAR2(100 CHAR)       NOT NULL,
    OBJECT_NAME      VARCHAR2(200 CHAR)       NOT NULL,
    DEFAULT_CHANNEL  VARCHAR2(30 CHAR)        DEFAULT 'IN_APP' NOT NULL, -- IN_APP|EMAIL|LOG|WEBHOOK
    SUBJECT_TEMPLATE VARCHAR2(400 CHAR),
    BODY_TEMPLATE    CLOB,
    DESCRIPTION      CLOB,
    VERSION_NO       NUMBER(10)               DEFAULT 1 NOT NULL,
    STATUS           VARCHAR2(30 CHAR)        DEFAULT 'DRAFT' NOT NULL,
    CREATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       RAW(16),
    UPDATED_BY       RAW(16),
    CONSTRAINT PK_NTF_NOTIFICATION PRIMARY KEY (OBJECT_ID),
    CONSTRAINT UK_NTF_NOTIFICATION_CODE UNIQUE (OBJECT_CODE)
);

-- Subscription: menghubungkan sebuah event bisnis ke notifikasi + aturan penerima.
CREATE TABLE IF NOT EXISTS NTF_SUBSCRIPTION (
    OBJECT_ID        RAW(16)                  DEFAULT SYS_GUID() NOT NULL,
    OBJECT_CODE      VARCHAR2(100 CHAR)       NOT NULL,
    OBJECT_NAME      VARCHAR2(200 CHAR)       NOT NULL,
    EVENT_CODE       VARCHAR2(150 CHAR)       NOT NULL,   -- mis. WF.WF_CUSTOMER_APPROVAL.SUBMIT
    NOTIFICATION_ID  RAW(16)                  NOT NULL,
    RECIPIENT_TYPE   VARCHAR2(30 CHAR)        NOT NULL,   -- ROLE|USER|OWNER|CURRENT
    RECIPIENT_REF    VARCHAR2(100 CHAR),                  -- kode role / username (untuk ROLE|USER)
    CHANNEL          VARCHAR2(30 CHAR),                   -- override channel (opsional)
    ACTIVE_FLAG      NUMBER(1)                DEFAULT 1 NOT NULL,
    DISPLAY_ORDER    NUMBER(10)               DEFAULT 0 NOT NULL,
    VERSION_NO       NUMBER(10)               DEFAULT 1 NOT NULL,
    STATUS           VARCHAR2(30 CHAR)        DEFAULT 'DRAFT' NOT NULL,
    CREATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       RAW(16),
    UPDATED_BY       RAW(16),
    CONSTRAINT PK_NTF_SUBSCRIPTION PRIMARY KEY (OBJECT_ID),
    CONSTRAINT UK_NTF_SUBSCRIPTION_CODE UNIQUE (OBJECT_CODE),
    CONSTRAINT CK_NTF_SUB_RECIPIENT CHECK (RECIPIENT_TYPE IN ('ROLE','USER','OWNER','CURRENT')),
    CONSTRAINT CK_NTF_SUB_ACTIVE CHECK (ACTIVE_FLAG IN (0, 1)),
    CONSTRAINT FK_NTF_SUB_NOTIFICATION FOREIGN KEY (NOTIFICATION_ID) REFERENCES NTF_NOTIFICATION (OBJECT_ID)
);

CREATE INDEX IF NOT EXISTS IDX_NTF_SUB_EVENT ON NTF_SUBSCRIPTION (EVENT_CODE);

-- --- Runtime: instance pengiriman notifikasi (in-app inbox) ----------------
CREATE TABLE IF NOT EXISTS RT_NOTIFICATION (
    OBJECT_ID          RAW(16)                DEFAULT SYS_GUID() NOT NULL,
    NOTIFICATION_ID    RAW(16),
    SUBSCRIPTION_CODE  VARCHAR2(100 CHAR),
    EVENT_CODE         VARCHAR2(150 CHAR),
    CHANNEL            VARCHAR2(30 CHAR)       NOT NULL,
    RECIPIENT_USER_ID  RAW(16),                            -- penerima (untuk IN_APP)
    SUBJECT            VARCHAR2(400 CHAR),
    BODY               CLOB,
    ENTITY_KEY         VARCHAR2(64 CHAR),                  -- baris bisnis terkait
    DELIVERY_STATUS    VARCHAR2(30 CHAR)      DEFAULT 'SENT' NOT NULL, -- PENDING|SENT|FAILED
    READ_FLAG          NUMBER(1)              DEFAULT 0 NOT NULL,
    CREATED_BY         RAW(16),
    CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    READ_AT            TIMESTAMP WITH TIME ZONE,
    CONSTRAINT PK_RT_NOTIFICATION PRIMARY KEY (OBJECT_ID),
    CONSTRAINT CK_RT_NTF_STATUS CHECK (DELIVERY_STATUS IN ('PENDING','SENT','FAILED')),
    CONSTRAINT CK_RT_NTF_READ CHECK (READ_FLAG IN (0, 1))
);

CREATE INDEX IF NOT EXISTS IDX_RT_NTF_RECIPIENT ON RT_NOTIFICATION (RECIPIENT_USER_ID, READ_FLAG);
CREATE INDEX IF NOT EXISTS IDX_RT_NTF_CREATED ON RT_NOTIFICATION (CREATED_AT);
