-- =============================================================================
-- 15. POS (Point of Sale) Tables
-- Tabel transaksi kasir untuk modul POS frontend
-- =============================================================================
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ODAF;

-- Header transaksi POS
CREATE TABLE IF NOT EXISTS POS_TRANSACTION (
    OBJECT_ID       RAW(16) DEFAULT SYS_GUID() NOT NULL,
    TRX_NO          VARCHAR2(30 CHAR) NOT NULL,
    TRX_DATE        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CASHIER_ID      RAW(16),
    CASHIER_NAME    VARCHAR2(200 CHAR),
    SUBTOTAL        NUMBER(15,2) DEFAULT 0 NOT NULL,
    DISCOUNT_AMOUNT NUMBER(15,2) DEFAULT 0,
    TAX_AMOUNT      NUMBER(15,2) DEFAULT 0,
    TOTAL_AMOUNT    NUMBER(15,2) DEFAULT 0 NOT NULL,
    PAYMENT_METHOD  VARCHAR2(20 CHAR) DEFAULT 'CASH' NOT NULL,
    AMOUNT_PAID     NUMBER(15,2) DEFAULT 0,
    CHANGE_AMOUNT   NUMBER(15,2) DEFAULT 0,
    STATUS          VARCHAR2(20 CHAR) DEFAULT 'COMPLETED' NOT NULL,
    NOTES           VARCHAR2(500 CHAR),
    CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_POS_TRX PRIMARY KEY (OBJECT_ID),
    CONSTRAINT UK_POS_TRX_NO UNIQUE (TRX_NO)
);

CREATE INDEX IDX_POS_TRX_DATE ON POS_TRANSACTION(TRX_DATE);
CREATE INDEX IDX_POS_TRX_CASHIER ON POS_TRANSACTION(CASHIER_ID);

-- Detail item transaksi POS
CREATE TABLE IF NOT EXISTS POS_TRANSACTION_ITEM (
    OBJECT_ID       RAW(16) DEFAULT SYS_GUID() NOT NULL,
    TRANSACTION_ID  RAW(16) NOT NULL,
    PRODUCT_ID      RAW(16),
    PRODUCT_CODE    VARCHAR2(50 CHAR),
    PRODUCT_NAME    VARCHAR2(200 CHAR),
    UNIT_PRICE      NUMBER(15,2) DEFAULT 0,
    QTY             NUMBER(10) DEFAULT 1 NOT NULL,
    DISCOUNT_PCT    NUMBER(5,2) DEFAULT 0,
    LINE_TOTAL      NUMBER(15,2) DEFAULT 0,
    CONSTRAINT PK_POS_TRX_ITEM PRIMARY KEY (OBJECT_ID),
    CONSTRAINT FK_POS_ITEM_TRX FOREIGN KEY (TRANSACTION_ID) REFERENCES POS_TRANSACTION(OBJECT_ID)
);

CREATE INDEX IDX_POS_TRX_ITEM_TRX ON POS_TRANSACTION_ITEM(TRANSACTION_ID);

-- Add CATEGORY column to PRODUCT table for POS filtering
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCT ADD (CATEGORY VARCHAR2(100 CHAR))';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -01430 THEN NULL; ELSE RAISE; END IF;
END;
/

-- Insert sample product data if empty
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, UNIT_PRICE, STOCK_QTY, CATEGORY)
SELECT SYS_GUID(), 'KOPI-001', 'Kopi Latte', 25000, 100, 'Minuman' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT WHERE PRODUCT_CODE = 'KOPI-001');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, UNIT_PRICE, STOCK_QTY, CATEGORY)
SELECT SYS_GUID(), 'KOPI-002', 'Kopi Americano', 20000, 100, 'Minuman' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT WHERE PRODUCT_CODE = 'KOPI-002');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, UNIT_PRICE, STOCK_QTY, CATEGORY)
SELECT SYS_GUID(), 'TEH-001', 'Teh Manis', 12000, 100, 'Minuman' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT WHERE PRODUCT_CODE = 'TEH-001');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, UNIT_PRICE, STOCK_QTY, CATEGORY)
SELECT SYS_GUID(), 'ROTI-001', 'Roti Bakar Coklat', 15000, 50, 'Makanan' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT WHERE PRODUCT_CODE = 'ROTI-001');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, UNIT_PRICE, STOCK_QTY, CATEGORY)
SELECT SYS_GUID(), 'ROTI-002', 'Roti Bakar Keju', 18000, 50, 'Makanan' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT WHERE PRODUCT_CODE = 'ROTI-002');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, UNIT_PRICE, STOCK_QTY, CATEGORY)
SELECT SYS_GUID(), 'NASI-001', 'Nasi Goreng Spesial', 28000, 30, 'Makanan' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT WHERE PRODUCT_CODE = 'NASI-001');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, UNIT_PRICE, STOCK_QTY, CATEGORY)
SELECT SYS_GUID(), 'MIE-001', 'Mie Goreng', 22000, 40, 'Makanan' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT WHERE PRODUCT_CODE = 'MIE-001');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, UNIT_PRICE, STOCK_QTY, CATEGORY)
SELECT SYS_GUID(), 'SUSU-001', 'Susu Segar', 15000, 60, 'Minuman' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT WHERE PRODUCT_CODE = 'SUSU-001');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, UNIT_PRICE, STOCK_QTY, CATEGORY)
SELECT SYS_GUID(), 'JUS-001', 'Jus Jeruk', 18000, 40, 'Minuman' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT WHERE PRODUCT_CODE = 'JUS-001');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, UNIT_PRICE, STOCK_QTY, CATEGORY)
SELECT SYS_GUID(), 'SNACK-001', 'Kentang Goreng', 20000, 30, 'Makanan' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT WHERE PRODUCT_CODE = 'SNACK-001');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, UNIT_PRICE, STOCK_QTY, CATEGORY)
SELECT SYS_GUID(), 'SNACK-002', 'Pisang Goreng', 12000, 25, 'Makanan' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT WHERE PRODUCT_CODE = 'SNACK-002');

INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, UNIT_PRICE, STOCK_QTY, CATEGORY)
SELECT SYS_GUID(), 'ES-001', 'Es Teh Manis', 8000, 100, 'Minuman' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT WHERE PRODUCT_CODE = 'ES-001');

COMMIT;
