-- =============================================================================
-- Migrasi: Mengganti status DEPRECATED menjadi ARCHIVED
-- =============================================================================

ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ODAF;

DECLARE
    v_count NUMBER;
BEGIN
    -- 1. Tambahkan ARCHIVED ke SYS_STATUS jika belum ada
    SELECT COUNT(*) INTO v_count FROM SYS_STATUS WHERE STATUS_CODE = 'ARCHIVED';
    IF v_count = 0 THEN
        INSERT INTO SYS_STATUS (STATUS_CODE, STATUS_NAME, DISPLAY_ORDER)
        VALUES ('ARCHIVED', 'Archived', 30);
    END IF;

    -- 2. Update tabel-tabel metadata yang mungkin memakai DEPRECATED
    EXECUTE IMMEDIATE 'UPDATE APP_APPLICATION SET STATUS = ''ARCHIVED'' WHERE STATUS = ''DEPRECATED''';
    EXECUTE IMMEDIATE 'UPDATE APP_MODULE SET STATUS = ''ARCHIVED'' WHERE STATUS = ''DEPRECATED''';
    EXECUTE IMMEDIATE 'UPDATE APP_MENU SET STATUS = ''ARCHIVED'' WHERE STATUS = ''DEPRECATED''';
    EXECUTE IMMEDIATE 'UPDATE UI_PAGE SET STATUS = ''ARCHIVED'' WHERE STATUS = ''DEPRECATED''';
    EXECUTE IMMEDIATE 'UPDATE UI_FIELD SET STATUS = ''ARCHIVED'' WHERE STATUS = ''DEPRECATED''';
    EXECUTE IMMEDIATE 'UPDATE DS_DATASET SET STATUS = ''ARCHIVED'' WHERE STATUS = ''DEPRECATED''';
    EXECUTE IMMEDIATE 'UPDATE DS_LOV SET STATUS = ''ARCHIVED'' WHERE STATUS = ''DEPRECATED''';
    EXECUTE IMMEDIATE 'UPDATE VAL_RULE SET STATUS = ''ARCHIVED'' WHERE STATUS = ''DEPRECATED''';
    EXECUTE IMMEDIATE 'UPDATE WF_WORKFLOW SET STATUS = ''ARCHIVED'' WHERE STATUS = ''DEPRECATED''';
    EXECUTE IMMEDIATE 'UPDATE NTF_NOTIFICATION SET STATUS = ''ARCHIVED'' WHERE STATUS = ''DEPRECATED''';
    EXECUTE IMMEDIATE 'UPDATE NTF_SUBSCRIPTION SET STATUS = ''ARCHIVED'' WHERE STATUS = ''DEPRECATED''';

    -- 3. Hapus DEPRECATED dari SYS_STATUS
    DELETE FROM SYS_STATUS WHERE STATUS_CODE = 'DEPRECATED';

END;
/
COMMIT;
