-- =============================================================================
-- Sample: LOV dependen (Customer Group) dari IFS via DB link @NEXUS + kolom baru
-- gvenzl menjalankan skrip ini sebagai SYS@CDB$ROOT; alihkan ke PDB & schema ODAF.
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ODAF;
--
-- CATATAN: DB link @NEXUS (IFSAPP) hanya tersedia di lingkungan produksi/IFS.
-- Di lingkungan demo tanpa link, LOV ini menghasilkan daftar kosong (aman).
-- Mekanisme parameter {{CUSTOMER_CODE}} & pengisian kolom label sudah aktif.
-- =============================================================================

-- 1. Kolom UI_FIELD.LOV_LABEL_COLUMN (tujuan penyimpanan label LOV).
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'UI_FIELD' AND COLUMN_NAME = 'LOV_LABEL_COLUMN';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE UI_FIELD ADD (LOV_LABEL_COLUMN VARCHAR2(128 CHAR))';
    END IF;
END;
/

-- 2. Kolom bisnis CUSTGROUP & CUSTGROUPDESC pada CUSTOMER.
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'CUSTOMER' AND COLUMN_NAME = 'CUSTGROUP';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE CUSTOMER ADD (CUSTGROUP VARCHAR2(50 CHAR), CUSTGROUPDESC VARCHAR2(200 CHAR))';
    END IF;
END;
/

-- 3. DS_LOV: Customer Group (SQL ke IFS via @NEXUS, parametrik {{CUSTOMER_CODE}}).
INSERT INTO DS_LOV (OBJECT_ID, OBJECT_CODE, OBJECT_NAME, LOV_TYPE, VALUE_COLUMN, LABEL_COLUMN, SOURCE_QUERY, STATUS)
SELECT HEXTORAW('00000000000000000000000000000070'), 'LOV_CUST_GROUP', 'Customer Group (IFS)',
       'SQL', 'CF$_CUSTGROUP', 'CF$_CUSTGROUPDESC',
       'SELECT CF$_CUSTGROUP, CF$_CUSTGROUPDESC FROM IFSAPP.CTM_CUST_GROUP_CLV@NEXUS WHERE CF$_CUSTGROUP = (SELECT CF$_CUSTGROUPID FROM IFSAPP.CUST_GROUP_DETAIL_CLV@NEXUS WHERE CF$_CUSTID = {{CUSTOMER_CODE}})',
       'PUBLISHED' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DS_LOV WHERE OBJECT_ID = HEXTORAW('00000000000000000000000000000070'));

-- 4. UI_FIELD "Customer Group": dropdown LOV; label disimpan ke CUSTGROUPDESC.
INSERT INTO UI_FIELD (OBJECT_ID, PAGE_ID, LOV_ID, LOV_LABEL_COLUMN, OBJECT_CODE, OBJECT_NAME, LABEL, COLUMN_NAME, FIELD_TYPE, DATA_TYPE, DISPLAY_ORDER, STATUS)
SELECT HEXTORAW('00000000000000000000000000000071'), HEXTORAW('00000000000000000000000000000030'),
       HEXTORAW('00000000000000000000000000000070'), 'CUSTGROUPDESC',
       'CUSTGROUP', 'Customer Group', 'Customer Group', 'CUSTGROUP', 'LOV', 'STRING', 50, 'PUBLISHED' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM UI_FIELD WHERE OBJECT_ID = HEXTORAW('00000000000000000000000000000071'));

-- 5. UI_FIELD "Customer Group (Deskripsi)": readonly, terisi otomatis dari label LOV.
INSERT INTO UI_FIELD (OBJECT_ID, PAGE_ID, OBJECT_CODE, OBJECT_NAME, LABEL, COLUMN_NAME, FIELD_TYPE, DATA_TYPE, DISPLAY_ORDER, READONLY_FLAG, STATUS)
SELECT HEXTORAW('00000000000000000000000000000072'), HEXTORAW('00000000000000000000000000000030'),
       'CUSTGROUPDESC', 'Customer Group Desc', 'Customer Group (Deskripsi)', 'CUSTGROUPDESC', 'TEXT', 'STRING', 60, 1, 'PUBLISHED' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM UI_FIELD WHERE OBJECT_ID = HEXTORAW('00000000000000000000000000000072'));

COMMIT;
